# Generated by Django 3.1.7 on 2021-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceController', '0003_auto_20210328_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='DEVICE_NAME',
            field=models.CharField(default='hospital_device', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='LOCATION',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
