# Generated by Django 3.1.7 on 2021-03-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceController', '0004_auto_20210328_2026'),
        ('DataController', '0002_auto_20210328_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heart_Rate',
            new_name='HeartRate',
        ),
    ]
