# Generated by Django 3.1.7 on 2021-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='ip_address',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
