# Generated by Django 3.1.7 on 2021-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceController', '0004_auto_20210328_2026'),
        ('DataController', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeartRate',
            new_name='Heart_Rate',
        ),
    ]
