# Generated by Django 3.1.7 on 2021-03-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceController', '0004_auto_20210328_2026'),
        ('DataController', '0003_auto_20210328_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.FloatField()),
                ('DATETIME', models.DateTimeField()),
                ('DEVICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceController.device')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.FloatField()),
                ('DATETIME', models.DateTimeField()),
                ('DEVICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceController.device')),
            ],
        ),
    ]
